### ISSUE TITLE
serial scan using scancode

### ISSUE THREAD

**Issue by vchhasatia** [awslabs/yesiscan#71]
iterator: cloning git: https://github.com/xxxx/xxxx @ HEAD into /home/username/.cache/yesiscan/git/35c6fd40531f86f516ecf4eac3e78f626ffce88a40228c6212bd1a80b4383063/
iterator: repo git: https://github.com/xxxx/xxxx @ HEAD already exists
iterator: default HEAD is at: master
iterator: running fs: /home/username/.cache/yesiscan/git/35c6fd40531f86f516ecf4eac3e78f626ffce88a40228c6212bd1a80b4383063/
core: scanner: scanning: /home/username/.cache/yesiscan/git/35c6fd40531f86f516ecf4eac3e78f626ffce88a40228c6212bd1a80b4383063/
core: scanner: scanning: /home/username/.cache/yesiscan/git/35c6fd40531f86f516ecf4eac3e78f626ffce88a40228c6212bd1a80b4383063/.travis.yml
backend: scancode got unexpected file: /home/username/.cache/yesiscan/git/35c6fd40531f86f516ecf4eac3e78f626ffce88a40228c6212bd1a80b4383063/.travis.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7a6339]goroutine 231 [running]:
[github.com/awslabs/yesiscan/backend.(*Scancode).ScanPath(0xc0000e22c0](http://github.com/awslabs/yesiscan/backend.(*Scancode).ScanPath(0xc0000e22c0), {0x1def9c8, 0xc000844480}, {0x1df0f40, 0xc000b500c0}, 0xc000b52020)
    /home/ANT.AMAZON.COM/purple/code/yesiscan/backend/scancode.go:188 +0xb19
[github.com/awslabs/yesiscan/lib.(*Scanner).Scan.func1({0x1de78a0](http://github.com/awslabs/yesiscan/lib.(*Scanner).Scan.func1(%7B0x1de78a0), 0xc0000e22c0})
    /home/ANT.AMAZON.COM/purple/code/yesiscan/lib/lib.go:403 +0x2e5
created by [github.com/awslabs/yesiscan/lib.(*Scanner).Scan](http://github.com/awslabs/yesiscan/lib.(*Scanner).Scan)
    /home/ANT.AMAZON.COM/purple/code/yesiscan/lib/lib.go:372 +0x4ed

**Comment by vchhasatia** [comment]
backend: scancode was expecting file: home/username/.cache/yesiscan/git/5d2fe004a6ed6ac3e3a48c2a705fb5427a3eeece8213e60f1207aec9b8c0bf4c/all.tgz
backend: scancode got unexpected file: /home/username/.cache/yesiscan/git/5d2fe004a6ed6ac3e3a48c2a705fb5427a3eeece8213e60f1207aec9b8c0bf4c/all.tgz
